### ISSUE TITLE
Many errors on GCC(G++)

### ISSUE THREAD

**Issue by rageworx** [jdthomas/bayer2rgb#4]
Your code has too many errors to build it with G++ ( 6.3.0 or higher on aarch64 )
Specially MIN, MAX, LIM macros not works correctly, and many typecasting erros to char to int.
And what meaning of "*restricted" ?
It should be fixed.
Please test on armhf(32bit) or aarch64(64bit) platforms of Linux.

**Comment by jdthomas** [comment]
Thanks for the report! Lol, this code is 11+ years old, feel free to put up patches :) 

It might still compile with a c compiler not c++. The `restrict` keyword is standard c that says a pointer is the only one into the underlying object (c99 section 6.7.3.1): https://stackoverflow.com/questions/745870/realistic-usage-of-the-c99-restrict-keyword 

Anyway, I would probably recommend against using this code, you're probably better off just using opencv or some better maintained library that offers demosaicing :) 

Cheers!

**Comment by MarekAtSense** [comment]
dcraw

**Comment by rageworx** [comment]
Yes, I did solve some bugs from your original codes for arm-linux-gcc aarch64 ( 6.4.x ).
I will share with you by clonning repo and  pulling request.
Thank You !

**Comment by rageworx** [comment]
Here I implemented your soruce to modern G++.
Thank you !
https://github.com/rageworx/bayer2rgb
